version: '2.2'
services:
  recommender:
    build: .
    image: recommender:gpu
    ports:
      - 8084:8084
    expose:
      - "8084"
    container_name: dojo-recommender
    networks:
      - rec
    volumes:
      - ./big_models_data_cache:/recommender/big_models_data_cache
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

networks:
  rec:
    driver: bridge
