version: '2.2'
services:
  recommender:
    build: .
    image: recommender:gpu
    ports:
    - mode: ingress
      target: 8084
      published: "8084"
      protocol: tcp
    restart: always
    container_name: dojo-recommender
    command:
    - poetry
    - run
    - uvicorn
    - topic_causality.api:app
    - --host
    - 0.0.0.0
    - --port
    - "8084"
    - --reload
    - --log-config
    - logging.yaml
    networks:
      - rec
    volumes:
      # - ./big_models_data_cache:/recommender/big_models_data_cache
      - type: bind
        source: .
        target: /recommender
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

networks:
  rec:
    driver: bridge
